### PR TITLE
Docker update v4.0.0 and workflow fix

### PR DESCRIPTION
**Pull request by ShankarWarang**
Update docker image from v3.3.x to v4.0.0

### CODE REVIEW

**Comment by remzrn** [comment]
lgtm

**Review by JelliedOwl — COMMENTED** [review]
Is it feasible to use a specific version rather than latest for eteissonniere/edgeware:latest, so that where were on v4.1.0 (say), someone can still pull the docker image for v4.0.0?

**Comment by ShankarWarang** [comment]
> Is it feasible to use a specific version rather than latest for eteissonniere/edgeware:latest, so that where we're on v4.1.0 (say), someone can still pull the docker image for v4.0.0?

I'm not sure if that's possible because these are 'daily builds' with no docker version tag at all. My guess is only one (latest) build is available to fetch at any time.

**Comment by remzrn** [comment]
Note that the docker part of the README is also outdated.

**Review by Depth-Hoar — APPROVED** [review]
looks good to me.

**Pull request merged**
