### PR TITLE
v4.0.0

### PR DESCRIPTION
**Pull request by ShankarWarang**
No more confusing terms like 'ERUP5', just `v4.0.0` to keep it simple and minimal!

- This PR consists of s few commits from previously proposed (but not merged on mainnet) ERUP4 and ERUP5 upgrades by Drew and Filip respectively as well as recent major commits by Remz to upgrade the core runtime to the **`Substrate v4`**.
- Related/fixed issues: #4, #20, #24, #25
- Previous pre-released: v3.5.1 {not merged on mainnet}
- Most recent community-approved merged release: Tokyo v3.2.0 {based on Substrate v2}
- Core runtime version: Substrate v4
- Polkadot version: v0.9.19
- Deprecating PRs: #22 and #26 
(Node v4.0.0 pre-release will be made after the merging to use it for the public testnet. The pre-release will be converted into a release when the upgrade is proposed on-chain to the community.)

### CODE REVIEW

**Comment by JelliedOwl** [comment]
As far as I can see, it all looks reasonable.  But it's a massive change and it's probably impossible to anyone to review everything here.  We know that this version seem to be working in the testnet, including apparently making the migrations correctly.

I've also double-checked that fees and staking rewards still look reasonable on the testnet after the runtime upgrade.

I can't guarantee I haven't missed something, but I'd go with this version.

**Review by JelliedOwl — APPROVED** [review]

**Review by Depth-Hoar — APPROVED** [review]

**Comment by ShankarWarang** [comment]
Reopening the branch after reverting the merge.

**Comment by ShankarWarang** [comment]
Reopening the PR after reverting the merge.

**Comment by flipchan** [comment]
can this be tested with the new tests? https://github.com/flipchan/edgeware-node/blob/erup-5-latest/ts-tests/new_tests/Readme.md

**Pull request merged**
